# shapefiles:
    # landuse: "data/shapefiles/texas-0915/gis_osm_landuse_a_free_1.shp"
    # traffic: "data/shapefiles/texas-0915/gis_osm_traffic_a_free_1.shp"
    # water: "data/shapefiles/texas-0915/gis_osm_water_a_free_1.shp"
    # waterways: "data/shapefiles/texas-0915/gis_osm_waterways_free_1.shp"
    # railways: "data/shapefiles/texas-0915/gis_osm_railways_free_1.shp"
    # roads: "data/shapefiles/texas-0915/gis_osm_roads_free_1.shp"
    # places: "data/shapefiles/texas-0915/gis_osm_places_a_free_1.shp"
    # buildings: "data/shapefiles/texas-0915/gis_osm_buildings_a_free_1.shp"


geojsons:
    landuse: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_landuse_a_free_1.geojson"
    traffic: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_traffic_a_free_1.geojson"
    water: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_water_a_free_1.geojson"
    waterways: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_waterways_free_1.geojson"
    railways: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_railways_free_1.geojson"
    roads: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_roads_free_1.geojson"
    places: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_places_a_free_1.geojson"
    buildings: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/gis_osm_buildings_a_free_1.geojson"
    landuse_complement: "/home/gridsan/qwang/urban-control/data/geojsons/dallas/landuse_complement.geojson"    
    
satellite_tile_control_base_dir: "/home/gridsan/qwang/urban-control/data/satellite_tiles_control_base/"
satellite_tile_control_seg_dir: "/home/gridsan/qwang/urban-control/data/satellite_tiles_seg_base/"
