landuse_mapping:
    residential: residential
    forest: forest
    industrial: industrial
    park: recreational
    commercial: commercial
    grass: recreational
    retail: commercial
    farmland: farmland
    meadow: farmland
    scrub: forest
    cemetery: recreational
    nature_reserve: forest
    recreation_ground: recreational
    farmyard: farmland
    parking: parking
    
building_residential_mapping:
    "house": "house"
    "apartments": "apartments"
    "terrace": "townhouse"
    "residential": "res_unkonwn"
    "detached": "house"

building_landuse_mapping: 
    "house": "residential"
    "apartments": "residential"
    "warehouse": "industrial"
    "industrial": "industrial"
    "commercial": "commercial"
    "retail": "commercial"
    "school": "commercial"
    "terrace": "residential"
    "parking": "parking"
    "church": "commercial"
    "residential": "residential"
    "office": "commercial"
    "detached": "residential"
    "static_caravan": "recreational" # todo - see if we need to change this
    "hospital": "commercial"
    "hotel": "commercial"
    "garage": "parking"
    "university": "commercial"
    "hangar": "industrial"
    "college": "commercial"
    "car_repair": "commercial"
    "civic": "recreational"
    "stadium": "commercial"
    "construction": "industrial"
    
layers_render: 
    water:
        stroke_color: "#a5bfdd"
        linewidth: 0.66
        fill_color: "#a5bfdd"
    waterways:
        stroke_color: "#a5bfdd"
        linewidth: 0.66
        fill_color: None
    railways:
        filters: 
            layer:
                geq: 0
        stroke_color: "#000000"
        linewidth: 2.4
        fill_color: None
    roads:
        filters: 
            layer:
                geq: 0
            fclass:
                - busway
                - motorway
                - primary
                - secondary
                - tertiary
                - trunk
                - motorway_link
                - primary_link
                - secondary_link
                - tertiary_link
                - trunk_link
        stroke_color: "#808080"
        linewidth: 1.2
        fill_color: None
        
    landuse_complement:
        residential: 
            fill_color: "#ed7d31" # orange
            stroke_color: "#ed7d31" # orange
            linewidth: 0
        commercial: 
            fill_color: "#5798d4" # blue
            stroke_color: "#5798d4" # blue
            linewidth: 0
        forest: 
            fill_color: "#385723" # dark green
            stroke_color: "#385723" # dark green
            linewidth: 0
        farmland: 
            fill_color: "#548235" # light green
            stroke_color: "#548235" # light green
            linewidth: 0
        recreational: 
            fill_color: "#d8604d" # coral
            stroke_color: "#d8604d" # coral
            linewidth: 0
        industrial: 
            fill_color: "#9566d6" # purple
            stroke_color: "#9566d6" # purple
            linewidth: 0
        parking: 
            fill_color: "#c7c7c7" # light gray
            stroke_color: "#c7c7c7" # light gray
            linewidth: 0

